# Essential Libraires

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [23]:
import warnings
warnings.filterwarnings('ignore')

Dataset Importing

In [24]:
df = pd.read_csv('/content/Iris.csv')
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
df.shape

(150, 6)

Preprocessing

In [26]:
df["Species"] = LabelEncoder().fit_transform(df["Species"])

In [27]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

## Model Testing

In [28]:
x = df.drop("Species",axis=1)
y = df["Species"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
lr_model = LogisticRegression()

lr_model.fit(x_train,y_train)

print("Model Accuracy:" ,accuracy_score(y_test,lr_model.predict(x_test)))
cm = confusion_matrix(y_test,lr_model.predict(x_test))
print(cm)

print(classification_report(y_test,lr_model.predict(x_test)))

Model Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [38]:
knn_model = KNeighborsClassifier()

knn_model.fit(x_train,y_train)

print("Model Accuracy:" ,accuracy_score(y_test,knn_model.predict(x_test)))
cm = confusion_matrix(y_test,knn_model.predict(x_test))
print(cm)

print(classification_report(y_test,knn_model.predict(x_test)))

Model Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [39]:
rf_model = RandomForestClassifier()

rf_model.fit(x_train,y_train)

print("Model Accuracy:" ,accuracy_score(y_test,rf_model.predict(x_test)))
cm = confusion_matrix(y_test,rf_model.predict(x_test))
print(cm)

print(classification_report(y_test,rf_model.predict(x_test)))

Model Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## Saving model

In [41]:
with open('irish.pkl','wb') as f:
  pickle.dump(lr_model,f)